### ISSUE TITLE
Guest Login Access in the ODCM world

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Specs#16]
![image](https://cloud.githubusercontent.com/assets/119096/26705799/d61c7fe6-477b-11e7-8092-09a01aad3882.png)

## What is a Guest?
A guest is a [special kind of user](https://octopus.com/docs/administration/authentication-providers/guest-login).
- They can move around the entire space and view *everything*. 
  - Projects
  - Configuration (users / audit / system / license / etc)
- They get to experience the process of editing right up until the point where they hit *save*, where they will be told it is not allowed

![image](https://cloud.githubusercontent.com/assets/119096/26705862/5417b65e-477c-11e7-959e-7576a92c76ca.png)

**Comment by NickJosevski** [comment]
In the case of supporting this feature in ODCM we have to consider/investigate a few more things.

## General Questions
 - How are people using this feature? _(aside from the Octopus use case of demo.octopus.com)_
 - Could they achieve the same by having a restricted user that they let people log in with by other means username/password?

## ODCM Specific
 - ODCM is Single Sign On access point, would customers expect to control guest access at a central location for all the spaces, and be able to turn it on/off broadly.
 - Actions required for authenticated users to logout of a space and then re-enter with guest access.
 - This has bigger implications for the future Hosted Octopus™

**Comment by vanessalove** [comment]
How I have seen this feature in use: (generally it is used in conjunction with AD)

When a company wants specific employees to see an Octopus instance without having direct access or login. Generally this has been an upper manager who just wants a look, or in some cases it can be around limits of license and user creation. Because anyone signing on with AD creates a user, large companies who had employees who found the Octopus installation and were curious about it just login, which would do a few things; 1. use up one of the login limits and 2. mean that user could potentially have access via the Everyone group to do things that never would have been given for that person. 
For 2. it means they do not have to maintain a 'viewers' group in AD and a team in Octopus.

**Comment by vanessalove** [comment]
example of a customer who uses guest https://secure.helpscout.net/conversation/374566717/16085/?folderId=557083

**Comment by droyad** [comment]
From that example:
> We by default want everyone in team to have VIEW access whenever someone tries to login to Octopus Web Portal without prompting them to login.

They are using Username/Password auth from the looks of it.

With Username/Password auth, you need to pre-create accounts, so I can see that causes some friction. 
With ODCM/Spaces, the only requirement would be that they have an account in whatever auth method is setup (eg AD/GoogleBusiness), if the admin has setup the "Everyone" group with access to the space.

In otherwords, to enable someone within an org to log in to a space, the admin would add the Everyone/AllUsers group as allowed to that space.

**Comment by droyad** [comment]
My argument against implementing this feature currently has three prongs.

The first is the unsubstantiated guess that guest accounts are currently being used so that user accounts do not need to be created in Octopus in advance, allowing all people on the network to log in. It also gets around the user licence limitation. 

Secondly, allowing unauthenticated access to a system seems wrong. With a guest account, anyone with physical access to the network (eg plugging in a cable, guest wifi or sniffing the wifi password), can access OD. Say an ex employee who knows the WIFI password sitting in the carpark.

Thirdly is how it would even work. Say a user has access to two spaces A and B. 
- How does the user choose whether to access the space using their account or the guest account?
- If we prompt the user the first time they visit a space, we lose the automatic login ability.
- If they switch to the guest account in A, does that mean they are now guest in B?
- How do we reconcile that the guest account may have more access than a user?
- Would it lead to confusion if the user was to switch to space C (which they don't have access to) and get guest access. They then realise they can't do anything, so get added to space C. Now they need to  somehow switch out of guest mode.

I think that if we instead make sure that the administrator can grant `All Authenticated Users` access to a space, all reasonable bases will be covered.

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.
