### ISSUE TITLE
What information/metrics should Spaces be reporting on?

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Specs#2]
For any given Space it can/should/will report on. So ODCM can aggregate them and report on *all spaces*.

Initial Scope (v1):
  - Online / offline status of itself
  - Online / offline status of its Environments

Extended (vNext):
 - License utilization (how much licence quota is remaining).
 - How many deployments grouped by time. 
 - Active users (seen in last, day, week, month).

What else would you like to see / find useful?

**Comment by NickJosevski** [comment]
See discussion on *how* with some coverage of what https://github.com/OctopusDeploy/Specs/issues/4

**Comment by lawrencewilson** [comment]
For troubleshooting purposes, I wouldn't mind seeing things like Errors and warnings against deployments, perhaps even scoped to a particular space.

**Comment by matt-richardson** [comment]
A few ideas of the top of my head:

* entity counts (eg, projects, environments, releases, deployments, users, etc)
* cpu usage
* memory usage
* disk space
* package counts
* success/failure rates of deployments
* feature usage??? (not sure about this)
* web request stats (counts, timings etc)

**Comment by NickJosevski** [comment]
I'll edit Matt's list above as we hear of more, example connection pool insides spaces, things like this may need reasonable amount of work inside OD to get that information out.

**Comment by thebigmoosey** [comment]
To accommodate reporting of both single and HA Spaces, we need to be careful about just plugging in a third-party reporting package. However I think we can come up with a hybrid approach that should work well...

## Perf considerations
To ensure we can maintain predictable load on your individual Octopus Servers (each Space), I'm recommending we add a new `Metrics` table to the database where we periodically feed in metrics from various sources.

In other words, have a reporting scheduler running every 30 minutes that takes a snapshot of the various metrics and feeds it into the `Metrics` table.

Reporting APIs can then be exposed with minimal performance risk (ie. API requests won't put pressure on important tables). Consumers like ODCM can then request reporting data via each Space's reporting API, and that API can simply query the metrics table only (nice and simple).

## Comparison analysis
This has the added advantage of allowing consumers to do comparison analysis of the metrics over time. Eg. _"Show me how many deployments we were doing in May compared to now"_, which I think for larger organizations would be quite interesting to show increased or decreased activity to whoever they're reporting to.

## Retention / cleanup
Since this would be storing data over time, we'd also add this table to our retention policies and clean up old data older than, say, 1 year.

## Reporting on entity counts
To report on database entities, we can create a view that consolidates all the entity counts into one query. Then we can query that view and see a snapshot of entity counts at that point in time (Eg. number of environments, machines, projects, releases, deployments, users, teams, tenants etc.). I'd probably keep this list fairly simple and only include entities related to either users/teams, environments/machines and projects/releases/deployments ... so start simple and wait for demand before adding too much else.

## Reporting on web request statistics
The Metrics.NET package plugs into our Nancy pipeline quite easily. From what I can tell, it saves all information in-memory on the given server, but you can tell it to periodically dump the metrics to a CSV file. So, in regards to HA setups, I'm thinking we can enable that CSV-dump feature, and each node will be saving metrics to a fileshare, similar to how our Octopus Server logs work with HA (eg. multiple nodes, all reporting to one shared server log). Then our reporting scheduler can process data from that shared CSV file when it needs to collect metrics.

Alternatively (and preferably imo) we can look into whether we can get Metrics.NET to periodically dump data straight into our `Metrics` table.

We can then look at exposing alternative endpoints to serve this data to various providers (like the formats expected by Prometheus etc).

## Reporting on active users
This may be difficult at present, as (to the best of my knowledge) we don't have a lastModifiedDate, loginDate or sessionHistory on users? We could add a "lastLoginDate" to the user resource, then figure out where best to update this as ppl login through the various providers.

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.
