### ISSUE TITLE
Is everything just a Tentacle?

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Specs#24]
Should the Orchestrator, Worker (#23), and/or Edge, just be a tentacle that has been configured on the server to perform that function (perhaps in addition to deployments)? 

The tentacle is already a run-anything component. We could package, distribute and invoke the Orchestrator, Worker, and/or Edge just like we do with Calamari.

**Advantages**
- This would make administration and upgrades very easy, we just push it out from the server
- A VM or Docker instance could serve as an Orchestrator or Worker as needed
- It has worked really well for deployments and is a known pattern
- We don't need to think about or do work on  the administrivia of running a process/service (eg communication setup, watchdog, install, upgrade)
 
**Disadvantages**
- The command line and Standard In/Out would be the only way of Tentacle <-> component communication which is low fidelity.
- Clean cancellation could be a bit tricky, at the moment we just kill Calamari to cancel a step

**Comment by MJRichardson** [comment]
It seems a safe bet that it will:

- Communicate via Halibut
- Run as a Service
- Push (or pull) the logic from the server to avoid manual upgrades

So it looks like a Tentacle, and walks like a Tentacle...

For the Orchestrator components, the limited communication-model (std-in/std-out) doesn't seem to be a big deal, as the communication will be mostly via the database.

Is it confusing to expose this functionality to customers as a Tentacle?  
In some ways it's _less_ confusing.  They are already familiar with Tentacles.

**Comment by matt-richardson** [comment]
> configured on the server
I'd be happier without this phrase in here (as it implies that its all local (which it _will_ be for a lot of installs) rather than "running somewhere")

> as the communication will be mostly via the database
This makes me feel icky - I hate integration at the database. We should ponder if we can avoid this.

We'd need to treat them differently in the api (as they aren't normal "machines"), and potentially treat them differently in the UI as well. Some of these components would be long running (i think), which doesn't fit the Tentacle model. They'd potentially need a separate installer/separate install location etc. Once they become special case enough, is it still worth it?

I'd vote that it _is_ more confusing, as customers see Tentacles as things that they install on target machines to deploy stuff. If we start using the same language for various server side components, it will definitely be confusing.

My initial starting place for this would be (would have been) that its a separate component, installed via the MSI as the same time as the server with communication via Halibut. We would use the same service installation/management as the server does, and upgrade at the same time as the server (ie, don't assume it has a separate life cycle).

Overall, it doesn't sit well with me, but the reasons listed are fairly compelling.

**Comment by matt-richardson** [comment]
Another thing to consider - in a container based world (ie, the hosted goal), we wont be worrying about services or watchdogs. Everything will just run as a console app, and if it dies, the container scheduler (ie kubernetes) will create a new one.

**Comment by droyad** [comment]
Putting nomenclature aside, I realised that the Worker is just a tentacle. It's this "blessed" tentacle we have been talking about. It only differs in that is registered differently.

@matt-richardson My initial design on #21 attempted to avoid that integration, but I don't think we can avoid it if you want the API, Task Runner and Scheduler as separate system.

Initially the Orchestrator was not going to talk to the database. But since it looks like we should roll the Orchestrator into the Task Runner, it will talk to the DB and filesystem directly.

So, should the Task Runner be a tentacle that receives a package and spawns the Task Runner?

**Advantages**
- It would make it trivial to upgrade the fleet of task runners
- We could take the idea we had with Calamari, and pin a release to a specific version of the task runner

**Disadvantages**
- Once the Task Runner is launched, the tentacle's only role is to tear it down when a new version is available

**Comment by droyad** [comment]
Closing this to continue this topic on each component.
