### ISSUE TITLE
The need for/capabilities of an Agent that runs alongside an Octopus Space

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Specs#6]
## Summary 
Definition: Agent - a separate process/service that is always running.

ODCM will need to perform some level of direct interactions with a given Space. We're trying to determine if an Agent needs to be built, deployed, maintained and run alongside each running Octopus Deploy instance. How do we achieve this?

## Story
Barry Infrastructure wants to have 50 spaces for a variety of teams, but is worried about the overhead of keeping those Spaces up to date, even via the ODCM user interface. 
The objective behind keeping the Spaces up to date is so teams can make use of the Space to Space sharing without running into incompatible version road blocks. 
Barry will be able to _toggle on or off_ any automated updates when such changes could be detrimental to a particular team - they're on a tight deadline and don't want additional risks.

## Case *for* the Agent:
1. It can be the trusted 2-way communication mechanism between the Space and ODCM
1. The agent for reporting purposes could extract (or modify data in/from the underlying database directly - likely to get out of hand quickly)
1. It can facilitate an tiered auto-update* mechanism
1. If multiple Octopus Spaces run on that machine, there's 1 Agent help interact with them (less communication point-to-point channels back to ODCM)

*Auto Update Options
- Level 1: Auto install patches
- Level 2: Auto install minor updates
- Level 3: Auto install any update

All can be configured to help perform Database backups.

## Case *against* the Agent:
1. Another set of code that needs to be maintained updated.
1. It needs to be able to update itself too (extra work).
1. Can remote PowerShell actions from the ODCM instance take away the need for another service.

**Comment by slewis74** [comment]
So the "agent" would be like an evolution of Octopus Server Manager, run as a service rather than UI (could still have a UI too for non-ODCM installs). It understands which instances are on the machine and can install new ones. It would support getting new binaries, vs just using the ones already in `C:\Program Files...`, and from here could support auto upgrade features.

If we can fit this in without complicating the non-ODCM installations it would address https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/3033637-upgrade-of-octopusserver-through-octopus

**Comment by matt-richardson** [comment]
If we do go down the path of having an agent, I'd like to see us try and use the DSC if at all possible. I'm not enthused to see yet another way to install and configure Octopus (we've already got way too many).

On a separate note, I'm ~a bit~ very scared about

> modify data in/from the underlying database directly

Integration at the database is very very painful.

**Comment by NickJosevski** [comment]
@matt-richardson your point is valid, I put it in there to discuss, but I would push that we make sure:
> All actions do occur via the Octopus Deploy API and NOT its database
 that way any new improvements required for functionality in ODCM also become features of a stand alone OD.

We're having discussions about actually making changes to how OD is installed, so this wouldn't be yet another way it would be the new way - I raised [this issue](https://github.com/OctopusDeploy/Specs/issues/8) where we'll put more details soon.

_(As a note on these issues I'm trying to scope their content so they can at some point soon be closed with a "final" decision once we've got enough feedback/consensus.)_

**Comment by matt-richardson** [comment]
I wonder if doing this in a way that support Octopus upgrading itself (as @slewis74 suggested) means that all ODCM has to do is call an api on the server, and it handles the upgrade itself? That would simplify the ODCM side of the equation quite a bit.

**Comment by droyad** [comment]
If ODCM managed this as per #8 upgrading would be easy

**Comment by ianpaullin** [comment]
I hate to minimize the question but isn't this just REST API calls to a specific space or today's octopus _instance_? How is an ODCM agent adding any more value than what the API already provides? It appears to me like the ODCM agent is akin to a tentacle agent. Being able to run scripts and do upgrades on any octopus instance/space can be done today with the tentacle agent. Let's look at the bullet points: 

1. _It can be the trusted 2-way communication mechanism between the Space and ODCM
The agent for reporting purposes could extract (or modify data in/from the underlying database directly - likely to get out of hand quickly)_ - reporting already comes from the API. I'm not sure why you'd want to modify reporting data per se, but that could just be more functionality added to the existing API. We currently have stored procs run against all our instance databases (320+) and we don't have any performance issues that we can detect so far. 

2. _It can facilitate an tiered auto-update* mechanism_ - this process needs to happen outside of the space, and therefore, theoretically it can run from the tentacle agent. Since ODCM itself is outside of the targeted space to be upgraded, initiating the upgrade could again be all done from within a tentacle agent.

3. _If multiple Octopus Spaces run on that machine, there's 1 Agent help interact with them (less communication point-to-point channels back to ODCM)_ - again, an agent can effectively run commands against the octopus.server.exe with the _--instance_ parameter targeting a specific space. How is this any more valuable than just running a tentacle agent?

I'm not saying outright there's no need for an ODCM agent. It just appears like all the points you've made could easily be _shimmed_ into a tentacle agent. Just my two cents. 

I'm starting to experiment auto upgrading our octopus instances simply by using a tentacle agent. From what I can tell, there's nothing really stopping me. We have a central Octopus server that has one tentacle agent on each of our Octopus HA nodes. The one tentacle agent running on that host is able to communicate to all the instances (spaces) on said host. We do it already today for all our custom automation. So why is an ODCM specific agent any better? Perhaps there's some optimizations that would be specific to ODCM which is one argument. But from what I've read, it looks like a tentacle agent covers most if not all this functionality.

**Comment by droyad** [comment]
@ianpaullin I think we are on the same page. The "agent" would be either a Tentacle or something very similar. It's main aim is to bypass any authentication/network issues that may exist. It's role would be to install/configure a space and so some basic service/memory/disk monitoring. See #9 for details.

**Comment by droyad** [comment]
In hindsight, I think this issue and #9 are essentially the same. I propose closing this issue.

**Comment by NickJosevski** [comment]
Closing this, more refined set of approaches to control spaces in #9
