### ISSUE TITLE
How a Space will be installed

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Specs#8]
This issue is to discuss how a space is installed (ie the Octopus Deploy instance). The mechanism on how access to the VM is gained is discussed in #9 

## Background
Currently we have an MSI to install Octopus Deploy and the OD Service must run with the instance flag, we rely on Registry Keys to determine folders, this will hamper efforts to run 2+ different versions of OD on the same VM/Machine.

## Proposed Changes
Using the "Agent" we've started discussing [here](https://github.com/OctopusDeploy/Specs/issues/6) or making changes to Octopus.Server.Manager.exe to unpack from a nuget package a version of OD. The feed can be remote hosted by Octopus/MyGet, or hosted by the ODCM for inside the network, with a `make offline package` option for a very locked down environments.

**Comment by droyad** [comment]
My thinking would be along the lines of:

1) Retrieve the package from the repository (see #11)
1) Transfer the package to the VM
1) Unpack the package to the install location
1) Create the config/working area
1) Apply directory permissions to restrict access to ODCM user and OD Service user
1) if it is a new space:
    a) Provision the DB if it is a new install (apply permissions as well)
    b) Generate a MasterKey
1) Install the service


Whether we use the registry: #10

**Comment by matt-richardson** [comment]
In the kind of environments we are targeting with ODCM, they will most likely already have a mechanism to deploy software like this. Whether its SCOM, Chef, Puppet, Ansible, DSC or one of many others.

For v1 at least, I'd suggest that we leave out installation, and let the consumer manage the installation. That way, we could use the MSI still, just with minor modifications to allow multiple versions side by side.

Side note: I'm not quite sure that the registry issue as defined is actually an issue? The only information stored is per instance, which doesn't impact instances having different versions? The MSI uses the registry to determine if its already installed and to uninstall/reinstall, so that part would have to be tackled.

**Comment by NickJosevski** [comment]
So long as we support easy enlistment for the scenario where customers would like to use their existing approach to "spin up" a space.

It can be just 1 additional command, the authentication concerns can be part of the enlistment action, it will need to start using the auth provider that talks to ODCM and stop using the existing ones.

`Octopus.server.exe -enslistWithOdcm="https://odcm-instance" --apiKeyForOdcm="keyABC"`

**Comment by droyad** [comment]
I think that one of the things that made Octopus so successful is that it just worked without the end user needing to invest large amounts of time into learning new technologies. The [upgrade Octopus](https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/3033637-upgrade-of-octopusserver-through-octopus) UserVoice has over 220 votes, so our customers are asking us to do something. 

**I think the goal should be that ODCM instance with several spaces can be setup within an hour by the average developer.**

That hour can easily be spent trying to figure out how the above mentioned technologies even operate. Why do our customers use Octopus instead of DSC/Chef. ODCM will already need to know about Virtual Machines, Spaces and Windows services, it's not a stretch to also allow it to manage the installation/upgrade of spaces.

Things like rolling an update out across a HA cluster (Drain and shutdown one node, upgrade it, drain and shut down others, start first node, upgrade rest) would be a lot easier to do imperatively.

I think we should build preliminary support in now for the beta and gauge customer feedback.

This feature would not restrict those who wanted to use DSC/Chef/etc from using those tools, they would just need to manage the lifecycle themselves.

**Comment by droyad** [comment]
The ability of the Space admin to self service an upgrade of their space

**Comment by matt-richardson** [comment]
Based on our conversation, i think its a case that the DSC/Chef part is a bit of a red herring. I'm more championing the idea of being agnostic about how the Octopus Server instance got installed (at least in the short term), and allowing it to be enlisted and then managed by ODCM.

**Comment by droyad** [comment]
Consensus from a team meeting is that, whatever path we go down, we should allow customers to use their own tools as well.

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.
